# Guassian Process w/ Customer Churn (Basic model)

### What is Guassian Process(GP)?

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score
from sklearn.model_selection import train_test_split

### Load, processed and prepare data

In [2]:
df = pd.read_csv('data.csv')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Quantity,Discount,Profit,Days Since First Order,lag_sales_1,lag_profit_1,rolling_sales_mean_3,rolling_profit_mean_3,cohort,churn
0,79,US-2014-147606,2014-11-26,2014-12-01,Second Class,JE-15745,Joel Eaton,Consumer,United States,Houston,...,5,0.6,-14.4750,0,97.0400,1.2130,316.092000,-42.551067,0,0
1,178,US-2015-101511,2015-11-21,2015-11-23,Second Class,JE-15745,Joel Eaton,Consumer,United States,Newark,...,7,0.3,-11.3372,360,19.3000,-14.4750,171.047333,-8.199733,12,0
2,235,US-2017-100930,2017-04-07,2017-04-12,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,3,0.2,0.0000,0,620.6145,-248.2458,370.848833,-116.764600,0,1
3,242,CA-2016-157749,2016-06-04,2016-06-09,Second Class,KL-16645,Ken Lonsdale,Consumer,United States,Chicago,...,5,0.5,-120.5130,680,11.6880,-4.6752,202.864333,-160.638733,23,1
4,243,CA-2016-157749,2016-06-04,2016-06-09,Second Class,KL-16645,Ken Lonsdale,Consumer,United States,Chicago,...,3,0.6,-2.8308,680,177.2250,-120.5130,64.319000,-42.673000,23,1

In [3]:
data = df.drop(columns = ['Row ID', 'Postal Code', 'cohort'])

In [4]:
numerical_columns = data.select_dtypes(include=['number']).columns.tolist()

In [5]:
data = df[numerical_columns]
data.head()

,Sales,Quantity,Discount,Profit,Days Since First Order,lag_sales_1,lag_profit_1,rolling_sales_mean_3,rolling_profit_mean_3,churn
0,19.300,5,0.6,-14.4750,0,97.0400,1.2130,316.092000,-42.551067,0
1,396.802,7,0.3,-11.3372,360,19.3000,-14.4750,171.047333,-8.199733,0
2,258.072,3,0.2,0.0000,0,620.6145,-248.2458,370.848833,-116.764600,1
3,177.225,5,0.5,-120.5130,680,11.6880,-4.6752,202.864333,-160.638733,1
4,4.044,3,0.6,-2.8308,680,177.2250,-120.5130,64.319000,-42.673000,1

In [6]:
features = data.columns.tolist()
target = 'churn'

In [7]:
X = data[features]
y = data[target]

In [8]:
# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [9]:
#Split the data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

### Define the Gaussian Process Model
The Radial Basis Function (RBF) kernel is commonly used

In [10]:
# Define the kernel: Constant * RBF
kernel = C(1.0) * RBF(length_scale=1.0)

In [11]:
gp_model = GaussianProcessClassifier(kernel=kernel, random_state=42)

In [12]:
gp_model.fit(X_train, y_train)

GaussianProcessClassifier(kernel=1**2 * RBF(length_scale=1), random_state=42)

### evalute model
We are using: cross validations in order to see our models preformance on multiple subsets of data

In [13]:
y_pred = gp_model.predict(X_test)

In [14]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 1.0000

In [109]:
# Calculate F1 score
f1 = f1_score(y_test, y_pred)
print(f"F1 Score: {f1:.4f}")

NameError: name 'f1_score' is not defined